### ISSUE TITLE
Questions & Comments

### ISSUE THREAD

**Issue by pavlin-policar** [biolab/point-annotator#5]
I've tried using this library and I have a few general comments that would, IMO, make this package much simple to use. To be clear, I was following the notebooks.

- You should add checks to make sure objects are of the correct type at the beginning of the script so it fails right away e.g. I passed in a sparse matrix instead of a dataframe and it was running for some time before it failed, and even then the message was quite cryptic.
- It's pretty strange you require the user to pass in a pandas dataframe, but then I thought about it a little and it makes sense since you need a way to match up the marker genes and the genes in the count matrix. Still, that caught me a little off guard.
- It seems strange to me that the annotations in the markers table need to have the name "Cell Type", after all, the library is called "point-annotator" and not "cell annotator". I think the most elegant solution would be to just allow a parameter `annotation_col`, which would allow me to quickly set and change which column I want to use for annotations.
- At first, I was completely confused by the `num_genes` parameter in `assign_annotations`. What does that have to do with anything? Reading the docstring did not help me out at all. Upon closer inspection, I realized that this is important for the DE test (I guess?). What would be the correct thing to do here if you don't know how many genes the organism has?
- You might want to add a function that does plotting with the annotations into the library itself. It's tedious to write code for plotting, and this is something most people would want to do (I guess).

Also, the notebooks are a little confusing, a lot of nontrivial code for plotting confusion matrices and all that. Other than that, it's really cool :smile:

**Comment by PrimozGodec** [comment]
@pavlin-policar, thank you for your comments. I agree with most of them and will fix them. :)

**Comment by PrimozGodec** [comment]
@pavlin-policar, I already considered first, third and fourth point of the issue in #6 . The main problem with names was that first, we implemented cell annotator and then we wanted to make it more general. It is my fault since I was not accurate enough while doing that. 

For the Pandas DataFrame, we decided since we wanted to avoid Orange data Tables in this package (to avoid a huge requirement). We thought DataFrame is a good alternative since it also holds columns names. 

Regarding plots: There is no direct method to do plotting of such data but I can make similar plots that appear in Notebooks. It would also simplify notebooks later. I will address this in separate PR.

**Comment by pavlin-policar** [comment]
Yes, I see the need for pandas data frames, my only concern was (and still is) with sparse data. From what I remember, pandas does a terrible job with sparse data, because I guess it does something with each column of the data, eating up a huge amount of memory. However, this may have been fixed in the meantime. So my concern is that if we have sc data with 20k genes, converting that to a Sparse data frame will still eat up too much memory.

As I said, plotting functions would be fantastic, and would make the notebooks easier to read, and would save people a lot of time, when trying to see the plot with annotations. I'd also suggest adding a parameter that allows you to choose the top K annotations for clusters.
